apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.serviceName }}
spec:
  selector:
    app: {{ .Values.postgres.appLabel }}
  ports:
    - protocol: TCP
      port: {{ .Values.postgres.servicePort }}
      targetPort: {{ .Values.postgres.targetPort }}
  type: {{ .Values.postgres.serviceType }}

