apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.todo.deploymentName }}
  labels:
    app: {{ .Values.todo.appLabel }}
spec:
  replicas: {{ .Values.todo.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.todo.appLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.todo.appLabel }}
    spec:
      containers:
        - name: {{ .Values.todo.containerName }}
          image: {{ .Values.todo.image }}
          ports:
            - containerPort: {{ .Values.todo.containerPort }}
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.todo.secretName }}
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.todo.secretName }}
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.todo.secretName }}
                  key: POSTGRES_DB
            - name: POSTGRES_HOST
              value: {{ .Values.todo.postgresHost }}

