# Todo app deployment
todo:
  deploymentName: todo-deployment
  appLabel: todo-app
  replicas: 2
  containerName: todo-app
  image: daviddocker526/todo_app_web:latest
  containerPort: 5000
  secretName: postgres-secret   # 👈 only reference

  # Service
  serviceName: todo-service
  servicePort: 5000
  targetPort: 5000
  serviceType: ClusterIP

  # Ingress
  ingressName: todo-ingress
  sslRedirect: "false"
  ingressClassName: nginx
  ingressPath: /
  ingressPathType: Prefix
  servicePort: 5000